# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  timeout: 5000

development_default: &development_default
  <<: *default
  <% if ENV['IS_REMOTE_DATABASE'] %>
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || "localhost" %>
  <% end %>

development:
  <<: *development_default
  database: <%= ENV['DATABASE_NAME'] || "mastermind-api" %>

test:
  <<: *development_default
  database: <%= ENV['DATABASE_NAME'] || "mastermind-api" %>test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>